apiVersion: v1alpha1
kind: Role
metadata:
  name: wishboard-role-anonymous
  labels:
    halo.run/hidden: "true"
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "心愿便签"
    rbac.authorization.halo.run/display-name: "心愿便签匿名访问"
rules:
  - apiGroups: ["anonymous.wishboard.aobp.cn"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: wishboard-role-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "心愿便签"
    rbac.authorization.halo.run/display-name: "心愿便签查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:wishboard:view"]
rules:
  - apiGroups: ["console.api.wishboard.aobp.cn"]
    resources: ["wishes"]
    verbs: ["get", "list"]
  - apiGroups: ["console.api.wishboard.aobp.cn"]
    resources: ["wishes/pending"]
    verbs: ["get", "list"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: wishboard-role-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "心愿便签"
    rbac.authorization.halo.run/display-name: "心愿便签管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:wishboard:manage"]
rules:
  - apiGroups: ["console.api.wishboard.aobp.cn"]
    resources: ["wishes", "wishes/approve", "wishes/reject", "wishes/-/export", "wishes/-/import", "wish-types", "wish-types/-/stats"]
    verbs: ["*"]
  - apiGroups: ["wishboard.aobp.cn"]
    resources: ["wishes", "wishtypes"]
    verbs: ["*"]
